# Generated by Django 3.2 on 2021-04-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_profile_picture'),
        ('authy', '0003_auto_20210426_1427'),
    ]

    operations = [
    ]
