# Generated by Django 3.2 on 2021-04-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_merge_20210426_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
